export interface AppAssetManifest {
    readonly precache: readonly string[];
    readonly calculatorFirstPaint: readonly string[];
}

const CALCULATOR_FIRST_PAINT_ASSETS = [
    "assets/calculator/body.webp",
    "assets/calculator/buttons/app_button_help.svg",
    "assets/calculator/buttons/app_button_home.svg",
    "assets/calculator/buttons/app_button_info.webp",
    "assets/calculator/buttons/app_button_rate.webp",
    "assets/calculator/buttons/app_button_settings.svg",
    "assets/calculator/buttons/app_button_settings_off.webp",
    "assets/calculator/buttons/app_button_settings_snd.webp",
    "assets/calculator/buttons/app_button_settings_snd_vbr.webp",
    "assets/calculator/buttons/app_button_settings_vbr.webp",
    "assets/calculator/buttons/app_button_share.webp",
    "assets/calculator/buttons/app_button_share_android.svg",
    "assets/calculator/buttons/app_button_share_ios.svg",
    "assets/calculator/buttons/button_clear.webp",
    "assets/calculator/buttons/button_digit.webp",
    "assets/calculator/buttons/button_func.webp",
    "assets/calculator/buttons/button_plus.webp",
    "assets/calculator/display/display_digit0.webp",
    "assets/calculator/display/display_digit1.webp",
    "assets/calculator/display/display_digit2.webp",
    "assets/calculator/display/display_digit3.webp",
    "assets/calculator/display/display_digit4.webp",
    "assets/calculator/display/display_digit5.webp",
    "assets/calculator/display/display_digit6.webp",
    "assets/calculator/display/display_digit7.webp",
    "assets/calculator/display/display_digit8.webp",
    "assets/calculator/display/display_digit9.webp",
    "assets/calculator/display/display_error.webp",
    "assets/calculator/display/display_memory.webp",
    "assets/calculator/display/display_minus.webp",
    "assets/calculator/display/display_point.webp",
    "assets/calculator/labels/label0.webp",
    "assets/calculator/labels/label1.webp",
    "assets/calculator/labels/label2.webp",
    "assets/calculator/labels/label3.webp",
    "assets/calculator/labels/label4.webp",
    "assets/calculator/labels/label5.webp",
    "assets/calculator/labels/label6.webp",
    "assets/calculator/labels/label7.webp",
    "assets/calculator/labels/label8.webp",
    "assets/calculator/labels/label9.webp",
    "assets/calculator/labels/label_ce_ca.webp",
    "assets/calculator/labels/label_change_sign.webp",
    "assets/calculator/labels/label_div.webp",
    "assets/calculator/labels/label_equals.webp",
    "assets/calculator/labels/label_mem_minus.webp",
    "assets/calculator/labels/label_mem_plus.webp",
    "assets/calculator/labels/label_minus.webp",
    "assets/calculator/labels/label_mrc.webp",
    "assets/calculator/labels/label_mu.webp",
    "assets/calculator/labels/label_mul.webp",
    "assets/calculator/labels/label_percent.webp",
    "assets/calculator/labels/label_plus.webp",
    "assets/calculator/labels/label_point.webp",
    "assets/calculator/labels/label_sqrt.webp",
] as const;
const PRECACHE_ASSETS_BEFORE_FIRST_PAINT_ASSETS = [
    "",
    "index.html",
    "manifest.webmanifest",
    "wasm/calculator.js",
    "wasm/calculator.wasm",
    "sounds/key-down.wav",
    "sounds/tap.wav",
    "favicon-48.png",
    "favicon-72.png",
    "favicon-96.png",
    "favicon-144.png",
    "favicon-192.png",
    "icons/icon-48.png",
    "icons/icon-72.png",
    "icons/icon-96.png",
    "icons/icon-144.png",
    "icons/icon-192.png",
    "icons/icon-512.png",
    "icons/maskable-icon-192.png",
    "icons/maskable-icon-512.png",
    "assets/settings/arrow-left.svg",
    "assets/settings/chevron-right.svg",
] as const;
export const calculatorFirstPaintAssets = CALCULATOR_FIRST_PAINT_ASSETS;

export const appAssetManifest = {
    precache: [
        ...PRECACHE_ASSETS_BEFORE_FIRST_PAINT_ASSETS,
        ...CALCULATOR_FIRST_PAINT_ASSETS,
    ],
    calculatorFirstPaint: CALCULATOR_FIRST_PAINT_ASSETS,
} as const satisfies AppAssetManifest;
